version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: { interval: weekly }
    groups:
      go-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /manager
    schedule: { interval: weekly }
    groups:
      manager-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
